//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newsApp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like_News
    {
        public int Id { get; set; }
        public int Id_user { get; set; }
        public int Id_news { get; set; }
        public int Value { get; set; }
    
        public virtual News News { get; set; }
        public virtual Users Users { get; set; }
    }
}
